"$schema" = "https://starship.rs/config-schema.json"

add_newline = true
command_timeout = 1200
scan_timeout = 25

format = """
[░▒▓](#00e5ff)\
[ ⚡ ](bg:#00e5ff fg:#00141a)\
[](fg:#00e5ff bg:#ff4fd8)\
$directory\
[](fg:#ff4fd8 bg:#7c3aed)\
$git_branch$git_status\
[](fg:#7c3aed bg:#2b59ff)\
$nodejs$python$rust$golang$dotnet$java$php\
[](fg:#2b59ff bg:#0f1b3d)\
$cmd_duration$time\
[ ](fg:#0f1b3d)\
\n$character"""

[username]
disabled = true

[hostname]
disabled = true

[directory]
style = "fg:#2b0031 bg:#ff4fd8"
format = "[ $path ]($style)"
truncation_length = 4
truncate_to_repo = false
truncation_symbol = ".../"

[git_branch]
symbol = ""
style = "bg:#7c3aed"
format = "[[ $symbol $branch ](fg:#f5d0fe bg:#7c3aed)]($style)"

[git_status]
style = "bg:#7c3aed"
format = "[[($all_status$ahead_behind )](fg:#fef08a bg:#7c3aed)]($style)"

[nodejs]
symbol = ""
style = "bg:#2b59ff"
format = "[[ $symbol ($version) ](fg:#dbeafe bg:#2b59ff)]($style)"

[python]
symbol = ""
style = "bg:#2b59ff"
format = "[[ $symbol ($version) ](fg:#dbeafe bg:#2b59ff)]($style)"

[rust]
symbol = ""
style = "bg:#2b59ff"
format = "[[ $symbol ($version) ](fg:#dbeafe bg:#2b59ff)]($style)"

[golang]
symbol = ""
style = "bg:#2b59ff"
format = "[[ $symbol ($version) ](fg:#dbeafe bg:#2b59ff)]($style)"

[dotnet]
symbol = ".NET"
style = "bg:#2b59ff"
format = "[[ $symbol ($version) ](fg:#dbeafe bg:#2b59ff)]($style)"

[java]
symbol = ""
style = "bg:#2b59ff"
format = "[[ $symbol ($version) ](fg:#dbeafe bg:#2b59ff)]($style)"

[php]
symbol = ""
style = "bg:#2b59ff"
format = "[[ $symbol ($version) ](fg:#dbeafe bg:#2b59ff)]($style)"

[cmd_duration]
min_time = 500
style = "bg:#0f1b3d"
format = "[[ took $duration ](fg:#00e5ff bg:#0f1b3d)]($style)"

[time]
disabled = false
time_format = "%H:%M"
style = "bg:#0f1b3d"
format = "[[  $time ](fg:#bfdbfe bg:#0f1b3d)]($style)"

[character]
success_symbol = "[>](bold fg:#00e5ff)"
error_symbol = "[>](bold fg:#fb7185)"
vimcmd_symbol = "[<](bold fg:#a3e635)"
