"$schema" = "https://starship.rs/config-schema.json"

add_newline = true
command_timeout = 1200
scan_timeout = 25

format = """
[░▒▓](#facc15)\
[ ⚡ ](bg:#facc15 fg:#2a1f00)\
[](fg:#facc15 bg:#86efac)\
$directory\
[](fg:#86efac bg:#2f3d2f)\
$git_branch$git_status\
[](fg:#2f3d2f bg:#233321)\
$nodejs$python$rust$golang$dotnet$java$php\
[](fg:#233321 bg:#162616)\
$cmd_duration$time\
[ ](fg:#162616)\
\n$character"""

[username]
disabled = true

[hostname]
disabled = true

[directory]
style = "fg:#0d2012 bg:#a3e635"
format = "[ $path ]($style)"
truncation_length = 4
truncate_to_repo = false
truncation_symbol = ".../"

[git_branch]
symbol = ""
style = "bg:#2f3d2f"
format = "[[ $symbol $branch ](fg:#fef08a bg:#2f3d2f)]($style)"

[git_status]
style = "bg:#2f3d2f"
format = "[[($all_status$ahead_behind )](fg:#facc15 bg:#2f3d2f)]($style)"

[nodejs]
symbol = ""
style = "bg:#233321"
format = "[[ $symbol ($version) ](fg:#d1fae5 bg:#233321)]($style)"

[python]
symbol = ""
style = "bg:#233321"
format = "[[ $symbol ($version) ](fg:#d1fae5 bg:#233321)]($style)"

[rust]
symbol = ""
style = "bg:#233321"
format = "[[ $symbol ($version) ](fg:#d1fae5 bg:#233321)]($style)"

[golang]
symbol = ""
style = "bg:#233321"
format = "[[ $symbol ($version) ](fg:#d1fae5 bg:#233321)]($style)"

[dotnet]
symbol = ".NET"
style = "bg:#233321"
format = "[[ $symbol ($version) ](fg:#d1fae5 bg:#233321)]($style)"

[java]
symbol = ""
style = "bg:#233321"
format = "[[ $symbol ($version) ](fg:#d1fae5 bg:#233321)]($style)"

[php]
symbol = ""
style = "bg:#233321"
format = "[[ $symbol ($version) ](fg:#d1fae5 bg:#233321)]($style)"

[cmd_duration]
min_time = 500
style = "bg:#162616"
format = "[[ took $duration ](fg:#fde047 bg:#162616)]($style)"

[time]
disabled = false
time_format = "%H:%M"
style = "bg:#162616"
format = "[[  $time ](fg:#fef3c7 bg:#162616)]($style)"

[character]
success_symbol = "[>](bold fg:#86efac)"
error_symbol = "[>](bold fg:#f59e0b)"
vimcmd_symbol = "[<](bold fg:#facc15)"
