"$schema" = "https://starship.rs/config-schema.json"

add_newline = true
command_timeout = 1200
scan_timeout = 25

format = """
[░▒▓](#8b5cf6)\
[ ⚡ ](bg:#8b5cf6 fg:#0f1720)\
[](fg:#8b5cf6 bg:#22c55e)\
$directory\
[](fg:#22c55e bg:#1f2937)\
$git_branch$git_status\
[](fg:#1f2937 bg:#172033)\
$nodejs$python$rust$golang$dotnet$java$php\
[](fg:#172033 bg:#111827)\
$cmd_duration$time\
[ ](fg:#111827)\
\n$character"""

[username]
disabled = true

[hostname]
disabled = true

[directory]
style = "fg:#0f1720 bg:#22c55e"
format = "[ $path ]($style)"
truncation_length = 4
truncate_to_repo = false
truncation_symbol = ".../"

[git_branch]
symbol = ""
style = "bg:#1f2937"
format = "[[ $symbol $branch ](fg:#ddd6fe bg:#1f2937)]($style)"

[git_status]
style = "bg:#1f2937"
format = "[[($all_status$ahead_behind )](fg:#fdba74 bg:#1f2937)]($style)"

[nodejs]
symbol = ""
style = "bg:#172033"
format = "[[ $symbol ($version) ](fg:#d1d5db bg:#172033)]($style)"

[python]
symbol = ""
style = "bg:#172033"
format = "[[ $symbol ($version) ](fg:#d1d5db bg:#172033)]($style)"

[rust]
symbol = ""
style = "bg:#172033"
format = "[[ $symbol ($version) ](fg:#d1d5db bg:#172033)]($style)"

[golang]
symbol = ""
style = "bg:#172033"
format = "[[ $symbol ($version) ](fg:#d1d5db bg:#172033)]($style)"

[dotnet]
symbol = ".NET"
style = "bg:#172033"
format = "[[ $symbol ($version) ](fg:#d1d5db bg:#172033)]($style)"

[java]
symbol = ""
style = "bg:#172033"
format = "[[ $symbol ($version) ](fg:#d1d5db bg:#172033)]($style)"

[php]
symbol = ""
style = "bg:#172033"
format = "[[ $symbol ($version) ](fg:#d1d5db bg:#172033)]($style)"

[cmd_duration]
min_time = 500
style = "bg:#111827"
format = "[[ took $duration ](fg:#22c55e bg:#111827)]($style)"

[time]
disabled = false
time_format = "%H:%M"
style = "bg:#111827"
format = "[[  $time ](fg:#d1d5db bg:#111827)]($style)"

[character]
success_symbol = "[>](bold fg:#22c55e)"
error_symbol = "[>](bold fg:#fb923c)"
vimcmd_symbol = "[<](bold fg:#8b5cf6)"
