"$schema" = "https://starship.rs/config-schema.json"

add_newline = true
command_timeout = 1200
scan_timeout = 25

format = """
[░▒▓](#a78bfa)\
[ ⚡ ](bg:#a78bfa fg:#1a1325)\
[](fg:#a78bfa bg:#f59e0b)\
$directory\
[](fg:#f59e0b bg:#3c2f5a)\
$git_branch$git_status\
[](fg:#3c2f5a bg:#2b223f)\
$nodejs$python$rust$golang$dotnet$java$php\
[](fg:#2b223f bg:#1f1a30)\
$cmd_duration$time\
[ ](fg:#1f1a30)\
\n$character"""

[username]
disabled = true

[hostname]
disabled = true

[directory]
style = "fg:#1a1325 bg:#f59e0b"
format = "[ $path ]($style)"
truncation_length = 4
truncate_to_repo = false
truncation_symbol = ".../"

[git_branch]
symbol = ""
style = "bg:#3c2f5a"
format = "[[ $symbol $branch ](fg:#e9d5ff bg:#3c2f5a)]($style)"

[git_status]
style = "bg:#3c2f5a"
format = "[[($all_status$ahead_behind )](fg:#fda4af bg:#3c2f5a)]($style)"

[nodejs]
symbol = ""
style = "bg:#2b223f"
format = "[[ $symbol ($version) ](fg:#ddd6fe bg:#2b223f)]($style)"

[python]
symbol = ""
style = "bg:#2b223f"
format = "[[ $symbol ($version) ](fg:#ddd6fe bg:#2b223f)]($style)"

[rust]
symbol = ""
style = "bg:#2b223f"
format = "[[ $symbol ($version) ](fg:#ddd6fe bg:#2b223f)]($style)"

[golang]
symbol = ""
style = "bg:#2b223f"
format = "[[ $symbol ($version) ](fg:#ddd6fe bg:#2b223f)]($style)"

[dotnet]
symbol = ".NET"
style = "bg:#2b223f"
format = "[[ $symbol ($version) ](fg:#ddd6fe bg:#2b223f)]($style)"

[java]
symbol = ""
style = "bg:#2b223f"
format = "[[ $symbol ($version) ](fg:#ddd6fe bg:#2b223f)]($style)"

[php]
symbol = ""
style = "bg:#2b223f"
format = "[[ $symbol ($version) ](fg:#ddd6fe bg:#2b223f)]($style)"

[cmd_duration]
min_time = 500
style = "bg:#1f1a30"
format = "[[ took $duration ](fg:#34d399 bg:#1f1a30)]($style)"

[time]
disabled = false
time_format = "%H:%M"
style = "bg:#1f1a30"
format = "[[  $time ](fg:#e9d5ff bg:#1f1a30)]($style)"

[character]
success_symbol = "[>](bold fg:#34d399)"
error_symbol = "[>](bold fg:#fda4af)"
vimcmd_symbol = "[<](bold fg:#f59e0b)"
