"$schema" = "https://starship.rs/config-schema.json"

add_newline = true
command_timeout = 1200
scan_timeout = 25

format = """
[░▒▓](#ff5ea8)\
[ ⚡ ](bg:#ff5ea8 fg:#2a0a1f)\
[](fg:#ff5ea8 bg:#ff9f1c)\
$directory\
[](fg:#ff9f1c bg:#a855f7)\
$git_branch$git_status\
[](fg:#a855f7 bg:#9333ea)\
$nodejs$python$rust$golang$dotnet$java$php\
[](fg:#9333ea bg:#7e22ce)\
$cmd_duration$time\
[ ](fg:#7e22ce)\
\n$character"""

[username]
disabled = true

[hostname]
disabled = true

[directory]
style = "fg:#2a1400 bg:#ff9f1c"
format = "[ $path ]($style)"
truncation_length = 4
truncate_to_repo = false
truncation_symbol = ".../"

[git_branch]
symbol = ""
style = "bg:#a855f7"
format = "[[ $symbol $branch ](fg:#ffffff bg:#a855f7)]($style)"

[git_status]
style = "bg:#a855f7"
format = "[[($all_status$ahead_behind )](fg:#fde68a bg:#a855f7)]($style)"

[nodejs]
symbol = ""
style = "bg:#9333ea"
format = "[[ $symbol ($version) ](fg:#f3e8ff bg:#9333ea)]($style)"

[python]
symbol = ""
style = "bg:#9333ea"
format = "[[ $symbol ($version) ](fg:#f3e8ff bg:#9333ea)]($style)"

[rust]
symbol = ""
style = "bg:#9333ea"
format = "[[ $symbol ($version) ](fg:#f3e8ff bg:#9333ea)]($style)"

[golang]
symbol = ""
style = "bg:#9333ea"
format = "[[ $symbol ($version) ](fg:#f3e8ff bg:#9333ea)]($style)"

[dotnet]
symbol = ".NET"
style = "bg:#9333ea"
format = "[[ $symbol ($version) ](fg:#f3e8ff bg:#9333ea)]($style)"

[java]
symbol = ""
style = "bg:#9333ea"
format = "[[ $symbol ($version) ](fg:#f3e8ff bg:#9333ea)]($style)"

[php]
symbol = ""
style = "bg:#9333ea"
format = "[[ $symbol ($version) ](fg:#f3e8ff bg:#9333ea)]($style)"

[cmd_duration]
min_time = 500
style = "bg:#7e22ce"
format = "[[ took $duration ](fg:#ffb454 bg:#7e22ce)]($style)"

[time]
disabled = false
time_format = "%H:%M"
style = "bg:#7e22ce"
format = "[[  $time ](fg:#ffe4a3 bg:#7e22ce)]($style)"

[character]
success_symbol = "[>](bold fg:#ffd166)"
error_symbol = "[>](bold fg:#ff5ea8)"
vimcmd_symbol = "[<](bold fg:#ff9f1c)"
